### ISSUE TITLE
Running simulation test error

### ISSUE THREAD

**Issue by airyimbin** [alexmnazarenko/pysimgrid#12]
After I installed everything I ran run_test.py for which I got "All tests passed!"
Whenever I try to run basic_test.py I get this:

    $ python basic_test.py
    Traceback (most recent call last):
      File "basic_test.py", line 18, in <module>
        from pysimgrid import simdag
      File "/home/tim/.local/lib/python2.7/site-packages/pysimgrid-1.0.0-py2.7-linux- 
    x86_64.egg/pysimgrid/__init__.py", line 19, in <module>
        from . import csimdag
    ImportError: /home/tim/.local/lib/python2.7/site-packages/pysimgrid-1.0.0-py2.7-linux- 
    x86_64.egg/pysimgrid/csimdag.so: undefined symbol: SD_dotload

I am running the py file inside the pysimgrid folder.
Running on Ubuntu 14.04 VM.

**Comment by alexmnazarenko** [comment]
Hi,

That's a well known problem, it happens if your Simgrid was built without graphviz support.

If you built it yourself, you just need to install 'libgraphviz-dev' (sudo apt-get install libgraphviz-dev) I believe and rebuild Simgrid.

**Comment by airyimbin** [comment]
Thanks that seemed to be the culprit with the undefined symbol error.
I'm now getting a new ImportError 

    $ python basic_test.py
    Traceback (most recent call last):
      File "basic_test.py", line 19, in <module>
        import pysimgrid.simdag.algorithms as algorithms
    ImportError: No module named algorithms

**Comment by airyimbin** [comment]
I solved the above error by saying `import simdag.algorithms as algorithms`
Now when I run basic_test.py it says
    
    $ python basic_test.py
    Traceback (most recent call last):
      File "basic_test.py", line 17, in <module>
      File "/home/tim/pysimgrid/pysimgrid/simdag/__init__.py", line 19, in <module>
        from ..csimdag import TaskKind
    ValueError: attempted relative import beyond top-level package

**Comment by alexmnazarenko** [comment]
Hm.

Mb some of the later changes broke py2 compatibility, I need to look on that.

Try py3?

**Comment by airyimbin** [comment]
I tried python3 I get the same error.
I tried running basic_test.py inside pysimgrid/pysimgrid and that got rid of cannot import 'csimdag'
If I run inside pysimgrid/pysimgrid it gives no module named algorithms.

I used python3 both times.

**Comment by airyimbin** [comment]
Basically I get import errors no matter where I position the basic_test.py file.
If you clone your current repo and try to run $ python3 basic_test.py where it is in the repo what happens for you?

**Comment by airyimbin** [comment]
Even when I run run_tests.py in pysimgrad/ where it currently is in the repo, I get `ImportError: cannot import name 'csimdag'` and I have to move it into pysimgrad/pysimgrad/ for it run and display "All test passed!"

**Comment by alexmnazarenko** [comment]
Mb it's install problem. Try in repo:

`python3 setup.py build_ext --inplace && python3 -B basic_test.py`
