### ISSUE TITLE
Error: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by msisched** [alexmnazarenko/pysimgrid#17]
I'm trying to run basic_test.py and I get the error:

Traceback (most recent call last):
  File "basic_test.py", line 18, in <module>
    from pysimgrid import simdag
  File "/pysimgrid-master/pysimgrid/__init__.py", line 19, in <module>
    from . import csimdag
ImportError: /pysimgrid-master/pysimgrid/csimdag.so: undefined symbol: _Py_ZeroStruct

Could you help me?
Thank you!!

**Comment by alexmnazarenko** [comment]
Hey,

it looks like you've used inconsistent python versions during build and execution. 

Make sure that
```setup.py build_ext ...``` stuff and ```basic_test.py``` are executed with same interpreter version (python vs python2 vs python3).

**Comment by msisched** [comment]
Thank you!

**Comment by saikaushik0410** [comment]
while i am running the model_main.py file for my training purpose , i get the following error: 
Traceback (most recent call last):
  File "model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/koushik/Desktop/fresh/models/research/object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "/home/koushik/Desktop/fresh/models/research/object_detection/eval_util.py", line 33, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/koushik/Desktop/fresh/models/research/object_detection/metrics/coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "/home/koushik/Desktop/fresh/models/research/object_detection/metrics/coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "/home/koushik/Desktop/fresh/models/research/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/koushik/Desktop/fresh/models/research/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /home/koushik/Desktop/fresh/models/research/pycocotools/_mask.so: undefined symbol: _Py_ZeroStruct
Can anyone provide me the solution
